{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sheeld.fullname" . }}-cp-postgres
  labels:
    {{- include "sheeld.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "sheeld.cpPostgres.selectorLabels" . | nindent 4 }}
{{- end }}
