apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sheeld.fullname" . }}-secret
  labels:
    {{- include "sheeld.labels" . | nindent 4 }}
type: Opaque
data:
  SHEELD_DATABASE_URL: {{ .Values.secrets.databaseURL | b64enc | quote }}
  SHEELD_JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  SHEELD_ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | b64enc | quote }}
